# Generated by Django 3.0 on 2020-02-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('pin_code', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cus_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cno', models.IntegerField()),
                ('city_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citcapp.CityModel')),
            ],
        ),
    ]
